theme: minima
title: JUST A TITLE
author: MMMYF
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Emm Hum... Nothing...
  Test
  Test

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  MYF2000 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
